[package]
name = "uttt"
version = "0.1.0"
authors = ["Andrew Briand <atb8888@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
